// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/chirp.tsx";
import * as $3 from "./routes/gallery/Background.tsx";
import * as $4 from "./routes/gallery/Button.tsx";
import * as $5 from "./routes/gallery/CodeBox.tsx";
import * as $6 from "./routes/gallery/ColoredButton.tsx";
import * as $7 from "./routes/gallery/Footer.tsx";
import * as $8 from "./routes/gallery/Header.tsx";
import * as $9 from "./routes/gallery/Input.tsx";
import * as $10 from "./routes/gallery/LinkButton.tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/index2.tsx";
import * as $$0 from "./islands/CopyArea.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Input.tsx";
import * as $$3 from "./islands/LemonDrop.tsx";
import * as $$4 from "./islands/Submit.tsx";
import * as $$5 from "./islands/Todo.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/chirp.tsx": $2,
    "./routes/gallery/Background.tsx": $3,
    "./routes/gallery/Button.tsx": $4,
    "./routes/gallery/CodeBox.tsx": $5,
    "./routes/gallery/ColoredButton.tsx": $6,
    "./routes/gallery/Footer.tsx": $7,
    "./routes/gallery/Header.tsx": $8,
    "./routes/gallery/Input.tsx": $9,
    "./routes/gallery/LinkButton.tsx": $10,
    "./routes/index.tsx": $11,
    "./routes/index2.tsx": $12,
  },
  islands: {
    "./islands/CopyArea.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Input.tsx": $$2,
    "./islands/LemonDrop.tsx": $$3,
    "./islands/Submit.tsx": $$4,
    "./islands/Todo.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
